spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{서버주소}/{데이터베이스 스키마}?serverTimezon=Asia/Seoul
    username: {유저이름}
    password: {암호}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: {클라이언트 아이디}
            client-secret: {클라이언트 시크릿}
            scope: # 네이버 스코프 항목 ( response를 제외하고 작성 ) [ https://developers.naver.com/docs/login/devguide/devguide.md#3-4-5-%EC%A0%91%EA%B7%BC-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-%ED%94%84%EB%A1%9C%ED%95%84-api-%ED%98%B8%EC%B6%9C%ED%95%98%EA%B8%B0 ]
              - email
              - username
              - gender
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://{서버주소}/login/oauth2/code/naver
          kakao:
            client-id: {클라이언트 아이디}
            client-authentication-method: POST
            scope: # 카카오 스코프 항목 [ https://developers.kakao.com/docs/latest/ko/kakaologin/prerequisite#personal-information ]
              - account_email
              - profile_nickname
              - gender
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://{서버주소}/login/oauth2/code/kakao
        provider:
          naver: # 네이버 Provider ( API를 받아오기 위한 주소 정보 )
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao: # 카카오 Provider ( API를 받아오기 위한 주소 정보 )
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id